package defpackage;

/* compiled from: r8-map-id-0b8713d1165be58ea5ab442262c023d7df2925fe25397b3c63a224cd7bc62647 */
/* loaded from: classes3.dex */
public abstract class bu0 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = y55.o;
        a = j2;
        b = y55.c;
        c = y55.d;
        d = y55.m;
        long j3 = y55.x;
        e = j3;
        f = y55.h;
        long j4 = y55.f;
        g = j4;
        h = y55.b;
        i = y55.a;
        j = y55.u;
        long j5 = y55.t;
        k = j5;
        l = j5;
        m = y55.v;
        n = y55.A;
        long j6 = y55.z;
        o = j6;
        p = j6;
        q = y55.B;
        r = j4;
        s = y55.p;
        t = y55.G;
        long j7 = y55.F;
        u = j7;
        v = j7;
        w = y55.H;
        x = y55.q;
        y = y55.r;
        z = y55.w;
        long j8 = y55.y;
        A = j8;
        B = j8;
        C = j3;
        D = y55.e;
        E = y55.C;
        long j9 = y55.E;
        F = j9;
        G = j9;
        H = y55.D;
        I = j2;
        J = j2;
        K = y55.l;
        L = y55.k;
        M = y55.j;
        N = y55.n;
        O = y55.g;
        P = y55.i;
        Q = y55.s;
        R = y55.I;
        long j10 = y55.K;
        S = j10;
        T = j10;
        U = y55.J;
    }
}
