package defpackage;

/* compiled from: r8-map-id-0b8713d1165be58ea5ab442262c023d7df2925fe25397b3c63a224cd7bc62647 */
/* loaded from: classes.dex */
public abstract class e58 {
    public static final long A;
    public static final long A0;
    public static final ol2 A1;
    public static final long B;
    public static final ke2 B0;
    public static final long B1;
    public static final long C;
    public static final ol2 C0;
    public static final long C1;
    public static final ke2 D;
    public static final long D0;
    public static final long D1;
    public static final ol2 E;
    public static final long E0;
    public static final ke2 E1;
    public static final long F;
    public static final long F0;
    public static final ol2 F1;
    public static final long G;
    public static final ke2 G0;
    public static final long G1;
    public static final long H;
    public static final ol2 H0;
    public static final long H1;
    public static final ke2 I;
    public static final long I0;
    public static final long I1;
    public static final ol2 J;
    public static final long J0;
    public static final ke2 J1;
    public static final long K;
    public static final long K0;
    public static final ol2 K1;
    public static final long L;
    public static final ke2 L0;
    public static final long L1;
    public static final long M;
    public static final ol2 M0;
    public static final long M1;
    public static final ke2 N;
    public static final long N0;
    public static final long N1;
    public static final ol2 O;
    public static final long O0;
    public static final ke2 O1;
    public static final long P;
    public static final long P0;
    public static final ol2 P1;
    public static final long Q;
    public static final ke2 Q0;
    public static final long Q1;
    public static final long R;
    public static final ol2 R0;
    public static final long R1;
    public static final ke2 S;
    public static final long S0;
    public static final long S1;
    public static final ol2 T;
    public static final long T0;
    public static final ke2 T1;
    public static final long U;
    public static final long U0;
    public static final long V;
    public static final ke2 V0;
    public static final long W;
    public static final ol2 W0;
    public static final ke2 X;
    public static final long X0;
    public static final ol2 Y;
    public static final long Y0;
    public static final long Z;
    public static final long Z0;
    public static final ol2 a;
    public static final long a0;
    public static final ke2 a1;
    public static final long b;
    public static final long b0;
    public static final ol2 b1;
    public static final long c;
    public static final ke2 c0;
    public static final long c1;
    public static final long d;
    public static final ol2 d0;
    public static final long d1;
    public static final ke2 e;
    public static final long e0;
    public static final long e1;
    public static final ol2 f;
    public static final long f0;
    public static final ke2 f1;
    public static final long g;
    public static final long g0;
    public static final ol2 g1;
    public static final long h;
    public static final ke2 h0;
    public static final long h1;
    public static final long i;
    public static final ol2 i0;
    public static final long i1;
    public static final ke2 j;
    public static final long j0;
    public static final long j1;
    public static final ol2 k;
    public static final long k0;
    public static final ke2 k1;
    public static final long l;
    public static final long l0;
    public static final ol2 l1;
    public static final long m;
    public static final ke2 m0;
    public static final long m1;
    public static final long n;
    public static final ol2 n0;
    public static final long n1;
    public static final ke2 o;
    public static final long o0;
    public static final long o1;
    public static final ol2 p;
    public static final long p0;
    public static final ke2 p1;
    public static final long q;
    public static final long q0;
    public static final ol2 q1;
    public static final long r;
    public static final ke2 r0;
    public static final long r1;
    public static final long s;
    public static final ol2 s0;
    public static final long s1;
    public static final ke2 t;
    public static final long t0;
    public static final long t1;
    public static final ol2 u;
    public static final long u0;
    public static final ke2 u1;
    public static final long v;
    public static final long v0;
    public static final ol2 v1;
    public static final long w;
    public static final ke2 w0;
    public static final long w1;
    public static final long x;
    public static final ol2 x0;
    public static final long x1;
    public static final ke2 y;
    public static final long y0;
    public static final long y1;
    public static final ol2 z;
    public static final long z0;
    public static final ke2 z1;

    static {
        ke2 ke2Var = g68.a;
        ol2 ol2Var = nd2.b;
        a = ol2Var;
        b = yu7.e(24.0d);
        c = yu7.f(16);
        d = yu7.e(0.5d);
        ke2 ke2Var2 = g68.c;
        e = ke2Var2;
        f = ol2Var;
        g = yu7.e(20.0d);
        h = yu7.f(14);
        i = yu7.e(0.2d);
        j = ke2Var2;
        k = ol2Var;
        l = yu7.e(16.0d);
        m = yu7.f(12);
        n = yu7.e(0.4d);
        o = ke2Var2;
        p = ol2Var;
        q = yu7.e(64.0d);
        r = yu7.f(57);
        long e2 = yu7.e(0.2d);
        yu7.c(e2);
        s = yu7.g(-xu7.c(e2), e2 & 1095216660480L);
        t = ke2Var2;
        u = ol2Var;
        v = yu7.e(52.0d);
        w = yu7.f(45);
        x = yu7.e(0.0d);
        y = ke2Var2;
        z = ol2Var;
        A = yu7.e(44.0d);
        B = yu7.f(36);
        C = yu7.e(0.0d);
        D = ke2Var2;
        E = ol2Var;
        F = yu7.e(40.0d);
        G = yu7.f(32);
        H = yu7.e(0.0d);
        I = ke2Var2;
        J = ol2Var;
        K = yu7.e(36.0d);
        L = yu7.f(28);
        M = yu7.e(0.0d);
        N = ke2Var2;
        O = ol2Var;
        P = yu7.e(32.0d);
        Q = yu7.f(24);
        R = yu7.e(0.0d);
        S = ke2Var2;
        T = ol2Var;
        U = yu7.e(20.0d);
        V = yu7.f(14);
        W = yu7.e(0.1d);
        ke2 ke2Var3 = g68.b;
        X = ke2Var3;
        Y = ol2Var;
        Z = yu7.e(16.0d);
        a0 = yu7.f(12);
        b0 = yu7.e(0.5d);
        c0 = ke2Var3;
        d0 = ol2Var;
        e0 = yu7.e(16.0d);
        f0 = yu7.f(11);
        g0 = yu7.e(0.5d);
        h0 = ke2Var3;
        i0 = ol2Var;
        j0 = yu7.e(28.0d);
        k0 = yu7.f(22);
        l0 = yu7.e(0.0d);
        m0 = ke2Var2;
        n0 = ol2Var;
        o0 = yu7.e(24.0d);
        p0 = yu7.f(16);
        q0 = yu7.e(0.2d);
        r0 = ke2Var3;
        s0 = ol2Var;
        t0 = yu7.e(20.0d);
        u0 = yu7.f(14);
        v0 = yu7.e(0.1d);
        w0 = ke2Var3;
        x0 = ol2Var;
        y0 = yu7.e(24.0d);
        z0 = yu7.f(16);
        A0 = yu7.e(0.15d);
        B0 = ke2Var3;
        C0 = ol2Var;
        D0 = yu7.e(20.0d);
        E0 = yu7.f(14);
        F0 = yu7.e(0.25d);
        G0 = ke2Var3;
        H0 = ol2Var;
        I0 = yu7.e(16.0d);
        J0 = yu7.f(12);
        K0 = yu7.e(0.4d);
        L0 = ke2Var3;
        M0 = ol2Var;
        N0 = yu7.e(64.0d);
        O0 = yu7.f(57);
        P0 = yu7.f(0);
        Q0 = ke2Var3;
        R0 = ol2Var;
        S0 = yu7.e(52.0d);
        T0 = yu7.f(45);
        U0 = yu7.f(0);
        V0 = ke2Var3;
        W0 = ol2Var;
        X0 = yu7.e(44.0d);
        Y0 = yu7.f(36);
        Z0 = yu7.f(0);
        a1 = ke2Var3;
        b1 = ol2Var;
        c1 = yu7.e(40.0d);
        d1 = yu7.f(32);
        e1 = yu7.f(0);
        f1 = ke2Var3;
        g1 = ol2Var;
        h1 = yu7.e(36.0d);
        i1 = yu7.f(28);
        j1 = yu7.f(0);
        k1 = ke2Var3;
        l1 = ol2Var;
        m1 = yu7.e(32.0d);
        n1 = yu7.f(24);
        o1 = yu7.f(0);
        p1 = ke2Var3;
        q1 = ol2Var;
        r1 = yu7.e(20.0d);
        s1 = yu7.f(14);
        t1 = yu7.e(0.1d);
        ke2 ke2Var4 = g68.a;
        u1 = ke2Var4;
        v1 = ol2Var;
        w1 = yu7.e(16.0d);
        x1 = yu7.f(12);
        y1 = yu7.e(0.5d);
        z1 = ke2Var4;
        A1 = ol2Var;
        B1 = yu7.e(16.0d);
        C1 = yu7.f(11);
        D1 = yu7.e(0.5d);
        E1 = ke2Var4;
        F1 = ol2Var;
        G1 = yu7.e(28.0d);
        H1 = yu7.f(22);
        I1 = yu7.f(0);
        J1 = ke2Var3;
        K1 = ol2Var;
        L1 = yu7.e(24.0d);
        M1 = yu7.f(16);
        N1 = yu7.e(0.15d);
        O1 = ke2Var4;
        P1 = ol2Var;
        Q1 = yu7.e(20.0d);
        R1 = yu7.f(14);
        S1 = yu7.e(0.1d);
        T1 = ke2Var4;
    }
}
