package defpackage;

import io.sentry.protocol.DebugImage;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.Set;

/* compiled from: r8-map-id-0b8713d1165be58ea5ab442262c023d7df2925fe25397b3c63a224cd7bc62647 */
/* loaded from: classes.dex */
public final class l47 {
    public static final nq0 A;
    public static final nq0 B;
    public static final jf2 a;
    public static final jf2 b;
    public static final jf2 c;
    public static final jf2 d;
    public static final jf2 e;
    public static final jf2 f;
    public static final jf2 g;
    public static final jf2 h;
    public static final jf2 i;
    public static final nq0 j;
    public static final nq0 k;
    public static final nq0 l;
    public static final nq0 m;
    public static final nq0 n;
    public static final nq0 o;
    public static final nq0 p;
    public static final nq0 q;
    public static final nq0 r;
    public static final nq0 s;
    public static final nq0 t;
    public static final nq0 u;
    public static final nq0 v;
    public static final Set w;
    public static final Set x;
    public static final nq0 y;
    public static final nq0 z;

    static {
        jf2 jf2Var = new jf2("kotlin");
        a = jf2Var;
        jf2 a2 = jf2Var.a(pr4.e("reflect"));
        b = a2;
        jf2Var.a(pr4.e("experimental"));
        jf2 a3 = jf2Var.a(pr4.e("collections"));
        c = a3;
        jf2Var.a(pr4.e("sequences"));
        jf2 a4 = jf2Var.a(pr4.e("ranges"));
        d = a4;
        jf2 a5 = jf2Var.a(pr4.e(DebugImage.JVM));
        jf2Var.a(pr4.e("js"));
        jf2Var.a(pr4.e("annotations")).a(pr4.e(DebugImage.JVM));
        a5.a(pr4.e("internal"));
        a5.a(pr4.e("functions"));
        jf2 a6 = jf2Var.a(pr4.e("annotation"));
        e = a6;
        jf2 a7 = jf2Var.a(pr4.e("internal"));
        f = a7.a(pr4.e("ir"));
        jf2 a8 = jf2Var.a(pr4.e("coroutines"));
        g = a8;
        a8.a(pr4.e("intrinsics"));
        h = jf2Var.a(pr4.e("enums"));
        jf2Var.a(pr4.e("contracts"));
        jf2 a9 = jf2Var.a(pr4.e("concurrent")).a(pr4.e("atomics"));
        i = a9;
        jf2Var.a(pr4.e("test"));
        jf2Var.a(pr4.e("text"));
        kt.Q0(new jf2[]{jf2Var, a3, a4, a6});
        kt.Q0(new jf2[]{jf2Var, a3, a4, a6, a2, a7, a8, a9});
        nn3.f("Nothing");
        j = nn3.f("Unit");
        k = nn3.f("Any");
        l = nn3.f("Enum");
        nn3.f("Annotation");
        m = nn3.f("Array");
        nq0 f2 = nn3.f("Boolean");
        n = f2;
        nq0 f3 = nn3.f("Char");
        nq0 f4 = nn3.f("Byte");
        nq0 f5 = nn3.f("Short");
        nq0 f6 = nn3.f("Int");
        o = f6;
        nq0 f7 = nn3.f("Long");
        p = f7;
        nq0 f8 = nn3.f("Float");
        nq0 f9 = nn3.f("Double");
        q = nn3.l(f4);
        r = nn3.l(f5);
        s = nn3.l(f6);
        t = nn3.l(f7);
        nn3.f("CharSequence");
        u = nn3.f("String");
        nn3.f("Throwable");
        nn3.f("Cloneable");
        nn3.k("KProperty");
        nn3.k("KMutableProperty");
        nn3.k("KProperty0");
        nn3.k("KMutableProperty0");
        nn3.k("KProperty1");
        nn3.k("KMutableProperty1");
        nn3.k("KProperty2");
        nn3.k("KMutableProperty2");
        v = nn3.k("KFunction");
        nn3.k("KClass");
        nn3.k("KCallable");
        nn3.k("KType");
        hi4.Q(pr4.e("Sequence")).a.c();
        nn3.f("Comparable");
        nn3.f("Number");
        nn3.f("Function");
        hi4.Q(pr4.e("SuspendFunction")).a.c();
        Set Q0 = kt.Q0(new nq0[]{f2, f3, f4, f5, f6, f7, f8, f9});
        w = Q0;
        kt.Q0(new nq0[]{f4, f5, f6, f7});
        Set set = Q0;
        int Y = vf4.Y(ut0.F0(set, 10));
        if (Y < 16) {
            Y = 16;
        }
        LinkedHashMap linkedHashMap = new LinkedHashMap(Y);
        for (Object obj : set) {
            linkedHashMap.put(obj, nn3.j(((nq0) obj).f()));
        }
        nn3.i(linkedHashMap);
        Set Q02 = kt.Q0(new nq0[]{q, r, s, t});
        x = Q02;
        Set set2 = Q02;
        int Y2 = vf4.Y(ut0.F0(set2, 10));
        LinkedHashMap linkedHashMap2 = new LinkedHashMap(Y2 >= 16 ? Y2 : 16);
        for (Object obj2 : set2) {
            linkedHashMap2.put(obj2, nn3.j(((nq0) obj2).f()));
        }
        nn3.i(linkedHashMap2);
        Set set3 = w;
        Set set4 = x;
        LinkedHashSet U = qt6.U(set3, set4);
        nq0 nq0Var = u;
        qt6.V(U, nq0Var);
        jf2 jf2Var2 = g;
        pr4 e2 = pr4.e("Continuation");
        jf2Var2.getClass();
        jf2 jf2Var3 = jf2.c;
        hi4.Q(e2).a.c();
        hi4.Q(pr4.e("CoroutineContext")).a.c();
        nn3.g("Iterator");
        nn3.g("Iterable");
        nn3.g("Collection");
        nn3.g("List");
        nn3.g("ListIterator");
        nn3.g("Set");
        nq0 g2 = nn3.g("Map");
        nn3.g("AbstractMap");
        nn3.g("MutableIterator");
        nn3.g("CharIterator");
        nn3.g("MutableIterable");
        nn3.g("MutableCollection");
        y = nn3.g("MutableList");
        nn3.g("MutableListIterator");
        z = nn3.g("MutableSet");
        nq0 g3 = nn3.g("MutableMap");
        A = g3;
        g2.d(pr4.e("Entry"));
        g3.d(pr4.e("MutableEntry"));
        nn3.f("Result");
        jf2 jf2Var4 = d;
        pr4 e3 = pr4.e("IntRange");
        jf2Var4.getClass();
        hi4.Q(e3).a.c();
        hi4.Q(pr4.e("LongRange")).a.c();
        hi4.Q(pr4.e("CharRange")).a.c();
        jf2 jf2Var5 = e;
        pr4 e4 = pr4.e("AnnotationRetention");
        jf2Var5.getClass();
        hi4.Q(e4).a.c();
        hi4.Q(pr4.e("AnnotationTarget")).a.c();
        nn3.f("DeprecationLevel");
        B = new nq0(h, pr4.e("EnumEntries"));
        nq0 e5 = nn3.e("AtomicBoolean");
        nq0 e6 = nn3.e("AtomicInt");
        nq0 e7 = nn3.e("AtomicLong");
        nn3.e("AtomicReference");
        w55 w55Var = new w55(n, e5);
        nq0 nq0Var2 = o;
        w55 w55Var2 = new w55(nq0Var2, e6);
        nq0 nq0Var3 = p;
        uf4.b0(w55Var, w55Var2, new w55(nq0Var3, e7));
        nn3.e("AtomicArray");
        uf4.b0(new w55(nq0Var2, nn3.e("AtomicIntArray")), new w55(nq0Var3, nn3.e("AtomicLongArray")));
        qt6.V(qt6.V(qt6.V(qt6.V(qt6.U(set3, set4), nq0Var), j), k), l);
    }
}
