package defpackage;

/* JADX INFO: compiled from: r8-map-id-bab227d27872676e62ff2ffe2fded003c9d885b8c3013765058fc121ecc85da5 */
/* JADX INFO: loaded from: classes3.dex */
public abstract class wm0 {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final long D;
    public static final long E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final long I;
    public static final long J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final long N;
    public static final long O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final long S;
    public static final long T;
    public static final long U;
    public static final long a;
    public static final long b;
    public static final long c;
    public static final long d;
    public static final long e;
    public static final long f;
    public static final long g;
    public static final long h;
    public static final long i;
    public static final long j;
    public static final long k;
    public static final long l;
    public static final long m;
    public static final long n;
    public static final long o;
    public static final long p;
    public static final long q;
    public static final long r;
    public static final long s;
    public static final long t;
    public static final long u;
    public static final long v;
    public static final long w;
    public static final long x;
    public static final long y;
    public static final long z;

    static {
        long j2 = defpackage.vn4.o;
        a = j2;
        b = defpackage.vn4.c;
        c = defpackage.vn4.d;
        d = defpackage.vn4.m;
        long j3 = defpackage.vn4.x;
        e = j3;
        f = defpackage.vn4.h;
        long j4 = defpackage.vn4.f;
        g = j4;
        h = defpackage.vn4.b;
        i = defpackage.vn4.a;
        j = defpackage.vn4.u;
        long j5 = defpackage.vn4.t;
        k = j5;
        l = j5;
        m = defpackage.vn4.v;
        n = defpackage.vn4.A;
        long j6 = defpackage.vn4.z;
        o = j6;
        p = j6;
        q = defpackage.vn4.B;
        r = j4;
        s = defpackage.vn4.p;
        t = defpackage.vn4.G;
        long j7 = defpackage.vn4.F;
        u = j7;
        v = j7;
        w = defpackage.vn4.H;
        x = defpackage.vn4.q;
        y = defpackage.vn4.r;
        z = defpackage.vn4.w;
        long j8 = defpackage.vn4.y;
        A = j8;
        B = j8;
        C = j3;
        D = defpackage.vn4.e;
        E = defpackage.vn4.C;
        long j9 = defpackage.vn4.E;
        F = j9;
        G = j9;
        H = defpackage.vn4.D;
        I = j2;
        J = j2;
        K = defpackage.vn4.l;
        L = defpackage.vn4.k;
        M = defpackage.vn4.j;
        N = defpackage.vn4.n;
        O = defpackage.vn4.g;
        P = defpackage.vn4.i;
        Q = defpackage.vn4.s;
        R = defpackage.vn4.I;
        long j10 = defpackage.vn4.K;
        S = j10;
        T = j10;
        U = defpackage.vn4.J;
    }
}
