package androidx.constraintlayout.widget;

import android.view.ViewGroup;
import defpackage.lt0;
import defpackage.mt0;
import defpackage.nt0;
import defpackage.ot0;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: compiled from: r8-map-id-bab227d27872676e62ff2ffe2fded003c9d885b8c3013765058fc121ecc85da5 */
/* JADX INFO: loaded from: /tmp/happ_dex/classes.dex */
public final class c {
    public int a;
    public final nt0 b;
    public final mt0 c;
    public final lt0 d;
    public final ot0 e;
    public HashMap f;

    public c() {
        nt0 nt0Var = new nt0();
        nt0Var.a = 0;
        nt0Var.b = 0;
        nt0Var.c = 1.0f;
        nt0Var.d = Float.NaN;
        this.b = nt0Var;
        mt0 mt0Var = new mt0();
        mt0Var.a = -1;
        mt0Var.b = 0;
        mt0Var.c = -1;
        mt0Var.d = Float.NaN;
        mt0Var.e = Float.NaN;
        mt0Var.f = Float.NaN;
        mt0Var.g = -1;
        mt0Var.h = null;
        mt0Var.i = -1;
        this.c = mt0Var;
        lt0 lt0Var = new lt0();
        lt0Var.a = false;
        lt0Var.d = -1;
        lt0Var.e = -1;
        lt0Var.f = -1.0f;
        lt0Var.g = true;
        lt0Var.h = -1;
        lt0Var.i = -1;
        lt0Var.j = -1;
        lt0Var.k = -1;
        lt0Var.l = -1;
        lt0Var.m = -1;
        lt0Var.n = -1;
        lt0Var.o = -1;
        lt0Var.p = -1;
        lt0Var.q = -1;
        lt0Var.r = -1;
        lt0Var.s = -1;
        lt0Var.t = -1;
        lt0Var.u = -1;
        lt0Var.v = -1;
        lt0Var.w = 0.5f;
        lt0Var.x = 0.5f;
        lt0Var.y = null;
        lt0Var.z = -1;
        lt0Var.A = 0;
        lt0Var.B = 0.0f;
        lt0Var.C = -1;
        lt0Var.D = -1;
        lt0Var.E = -1;
        lt0Var.F = 0;
        lt0Var.G = 0;
        lt0Var.H = 0;
        lt0Var.I = 0;
        lt0Var.J = 0;
        lt0Var.K = 0;
        lt0Var.L = 0;
        lt0Var.M = Integer.MIN_VALUE;
        lt0Var.N = Integer.MIN_VALUE;
        lt0Var.O = Integer.MIN_VALUE;
        lt0Var.P = Integer.MIN_VALUE;
        lt0Var.Q = Integer.MIN_VALUE;
        lt0Var.R = Integer.MIN_VALUE;
        lt0Var.S = Integer.MIN_VALUE;
        lt0Var.T = -1.0f;
        lt0Var.U = -1.0f;
        lt0Var.V = 0;
        lt0Var.W = 0;
        lt0Var.X = 0;
        lt0Var.Y = 0;
        lt0Var.Z = 0;
        lt0Var.a0 = 0;
        lt0Var.b0 = 0;
        lt0Var.c0 = 0;
        lt0Var.d0 = 1.0f;
        lt0Var.e0 = 1.0f;
        lt0Var.f0 = -1;
        lt0Var.g0 = 0;
        lt0Var.h0 = -1;
        lt0Var.l0 = false;
        lt0Var.m0 = false;
        lt0Var.n0 = true;
        lt0Var.o0 = 0;
        this.d = lt0Var;
        ot0 ot0Var = new ot0();
        ot0Var.a = 0.0f;
        ot0Var.b = 0.0f;
        ot0Var.c = 0.0f;
        ot0Var.d = 1.0f;
        ot0Var.e = 1.0f;
        ot0Var.f = Float.NaN;
        ot0Var.g = Float.NaN;
        ot0Var.h = -1;
        ot0Var.i = 0.0f;
        ot0Var.j = 0.0f;
        ot0Var.k = 0.0f;
        ot0Var.l = false;
        ot0Var.m = 0.0f;
        this.e = ot0Var;
        this.f = new HashMap();
    }

    public final void a(ConstraintLayout.LayoutParams layoutParams) {
        lt0 lt0Var = this.d;
        layoutParams.e = lt0Var.h;
        layoutParams.f = lt0Var.i;
        layoutParams.g = lt0Var.j;
        layoutParams.h = lt0Var.k;
        layoutParams.i = lt0Var.l;
        layoutParams.j = lt0Var.m;
        layoutParams.k = lt0Var.n;
        layoutParams.l = lt0Var.o;
        layoutParams.m = lt0Var.p;
        layoutParams.n = lt0Var.q;
        layoutParams.o = lt0Var.r;
        layoutParams.s = lt0Var.s;
        layoutParams.t = lt0Var.t;
        layoutParams.u = lt0Var.u;
        layoutParams.v = lt0Var.v;
        ((ViewGroup.MarginLayoutParams) layoutParams).leftMargin = lt0Var.F;
        ((ViewGroup.MarginLayoutParams) layoutParams).rightMargin = lt0Var.G;
        ((ViewGroup.MarginLayoutParams) layoutParams).topMargin = lt0Var.H;
        ((ViewGroup.MarginLayoutParams) layoutParams).bottomMargin = lt0Var.I;
        layoutParams.A = lt0Var.R;
        layoutParams.B = lt0Var.Q;
        layoutParams.x = lt0Var.N;
        layoutParams.z = lt0Var.P;
        layoutParams.E = lt0Var.w;
        layoutParams.F = lt0Var.x;
        layoutParams.p = lt0Var.z;
        layoutParams.q = lt0Var.A;
        layoutParams.r = lt0Var.B;
        layoutParams.G = lt0Var.y;
        layoutParams.T = lt0Var.C;
        layoutParams.U = lt0Var.D;
        layoutParams.I = lt0Var.T;
        layoutParams.H = lt0Var.U;
        layoutParams.K = lt0Var.W;
        layoutParams.J = lt0Var.V;
        layoutParams.W = lt0Var.l0;
        layoutParams.X = lt0Var.m0;
        layoutParams.L = lt0Var.X;
        layoutParams.M = lt0Var.Y;
        layoutParams.P = lt0Var.Z;
        layoutParams.Q = lt0Var.a0;
        layoutParams.N = lt0Var.b0;
        layoutParams.O = lt0Var.c0;
        layoutParams.R = lt0Var.d0;
        layoutParams.S = lt0Var.e0;
        layoutParams.V = lt0Var.E;
        layoutParams.c = lt0Var.f;
        layoutParams.a = lt0Var.d;
        layoutParams.b = lt0Var.e;
        ((ViewGroup.MarginLayoutParams) layoutParams).width = lt0Var.b;
        ((ViewGroup.MarginLayoutParams) layoutParams).height = lt0Var.c;
        String str = lt0Var.k0;
        if (str != null) {
            layoutParams.Y = str;
        }
        layoutParams.Z = lt0Var.o0;
        layoutParams.setMarginStart(lt0Var.K);
        layoutParams.setMarginEnd(lt0Var.J);
        layoutParams.a();
    }

    public final Object clone() {
        c cVar = new c();
        lt0 lt0Var = cVar.d;
        lt0Var.getClass();
        lt0 lt0Var2 = this.d;
        lt0Var.a = lt0Var2.a;
        lt0Var.b = lt0Var2.b;
        lt0Var.c = lt0Var2.c;
        lt0Var.d = lt0Var2.d;
        lt0Var.e = lt0Var2.e;
        lt0Var.f = lt0Var2.f;
        lt0Var.g = lt0Var2.g;
        lt0Var.h = lt0Var2.h;
        lt0Var.i = lt0Var2.i;
        lt0Var.j = lt0Var2.j;
        lt0Var.k = lt0Var2.k;
        lt0Var.l = lt0Var2.l;
        lt0Var.m = lt0Var2.m;
        lt0Var.n = lt0Var2.n;
        lt0Var.o = lt0Var2.o;
        lt0Var.p = lt0Var2.p;
        lt0Var.q = lt0Var2.q;
        lt0Var.r = lt0Var2.r;
        lt0Var.s = lt0Var2.s;
        lt0Var.t = lt0Var2.t;
        lt0Var.u = lt0Var2.u;
        lt0Var.v = lt0Var2.v;
        lt0Var.w = lt0Var2.w;
        lt0Var.x = lt0Var2.x;
        lt0Var.y = lt0Var2.y;
        lt0Var.z = lt0Var2.z;
        lt0Var.A = lt0Var2.A;
        lt0Var.B = lt0Var2.B;
        lt0Var.C = lt0Var2.C;
        lt0Var.D = lt0Var2.D;
        lt0Var.E = lt0Var2.E;
        lt0Var.F = lt0Var2.F;
        lt0Var.G = lt0Var2.G;
        lt0Var.H = lt0Var2.H;
        lt0Var.I = lt0Var2.I;
        lt0Var.J = lt0Var2.J;
        lt0Var.K = lt0Var2.K;
        lt0Var.L = lt0Var2.L;
        lt0Var.M = lt0Var2.M;
        lt0Var.N = lt0Var2.N;
        lt0Var.O = lt0Var2.O;
        lt0Var.P = lt0Var2.P;
        lt0Var.Q = lt0Var2.Q;
        lt0Var.R = lt0Var2.R;
        lt0Var.S = lt0Var2.S;
        lt0Var.T = lt0Var2.T;
        lt0Var.U = lt0Var2.U;
        lt0Var.V = lt0Var2.V;
        lt0Var.W = lt0Var2.W;
        lt0Var.X = lt0Var2.X;
        lt0Var.Y = lt0Var2.Y;
        lt0Var.Z = lt0Var2.Z;
        lt0Var.a0 = lt0Var2.a0;
        lt0Var.b0 = lt0Var2.b0;
        lt0Var.c0 = lt0Var2.c0;
        lt0Var.d0 = lt0Var2.d0;
        lt0Var.e0 = lt0Var2.e0;
        lt0Var.f0 = lt0Var2.f0;
        lt0Var.g0 = lt0Var2.g0;
        lt0Var.h0 = lt0Var2.h0;
        lt0Var.k0 = lt0Var2.k0;
        int[] iArr = lt0Var2.i0;
        if (iArr == null || lt0Var2.j0 != null) {
            lt0Var.i0 = null;
        } else {
            lt0Var.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        lt0Var.j0 = lt0Var2.j0;
        lt0Var.l0 = lt0Var2.l0;
        lt0Var.m0 = lt0Var2.m0;
        lt0Var.n0 = lt0Var2.n0;
        lt0Var.o0 = lt0Var2.o0;
        mt0 mt0Var = cVar.c;
        mt0Var.getClass();
        mt0 mt0Var2 = this.c;
        mt0Var2.getClass();
        mt0Var.a = mt0Var2.a;
        mt0Var.c = mt0Var2.c;
        mt0Var.e = mt0Var2.e;
        mt0Var.d = mt0Var2.d;
        nt0 nt0Var = this.b;
        int i = nt0Var.a;
        nt0 nt0Var2 = cVar.b;
        nt0Var2.a = i;
        nt0Var2.c = nt0Var.c;
        nt0Var2.d = nt0Var.d;
        nt0Var2.b = nt0Var.b;
        ot0 ot0Var = cVar.e;
        ot0Var.getClass();
        ot0 ot0Var2 = this.e;
        ot0Var2.getClass();
        ot0Var.a = ot0Var2.a;
        ot0Var.b = ot0Var2.b;
        ot0Var.c = ot0Var2.c;
        ot0Var.d = ot0Var2.d;
        ot0Var.e = ot0Var2.e;
        ot0Var.f = ot0Var2.f;
        ot0Var.g = ot0Var2.g;
        ot0Var.h = ot0Var2.h;
        ot0Var.i = ot0Var2.i;
        ot0Var.j = ot0Var2.j;
        ot0Var.k = ot0Var2.k;
        ot0Var.l = ot0Var2.l;
        ot0Var.m = ot0Var2.m;
        cVar.a = this.a;
        return cVar;
    }
}
