package org.conscrypt.metrics;

/* compiled from: r8-map-id-0b8713d1165be58ea5ab442262c023d7df2925fe25397b3c63a224cd7bc62647 */
/* loaded from: classes.dex */
public enum CipherSuite {
    UNKNOWN_CIPHER_SUITE(0),
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA),
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA),
    TLS_RSA_WITH_AES_256_CBC_SHA(53),
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA),
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA),
    TLS_RSA_WITH_AES_128_CBC_SHA(47),
    TLS_RSA_WITH_3DES_EDE_CBC_SHA(10),
    TLS_RSA_WITH_AES_128_GCM_SHA256(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_RSA_WITH_AES_128_GCM_SHA256),
    TLS_RSA_WITH_AES_256_GCM_SHA384(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_RSA_WITH_AES_256_GCM_SHA384),
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256),
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384),
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256),
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384),
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256),
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256),
    TLS_PSK_WITH_AES_128_CBC_SHA(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_PSK_WITH_AES_128_CBC_SHA),
    TLS_PSK_WITH_AES_256_CBC_SHA(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_PSK_WITH_AES_256_CBC_SHA),
    TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA),
    TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA),
    TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256),
    TLS_AES_128_GCM_SHA256(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_AES_128_GCM_SHA256),
    TLS_AES_256_GCM_SHA384(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_AES_256_GCM_SHA384),
    TLS_CHACHA20_POLY1305_SHA256(ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_CHACHA20_POLY1305_SHA256),
    TLS_CIPHER_FAILED(65535);

    final int id;

    CipherSuite(int i) {
        this.id = i;
    }

    public static CipherSuite forName(String str) {
        if ("SSL_RSA_WITH_3DES_EDE_CBC_SHA".equals(str)) {
            return TLS_RSA_WITH_3DES_EDE_CBC_SHA;
        }
        try {
            return valueOf(str);
        } catch (IllegalArgumentException unused) {
            return UNKNOWN_CIPHER_SUITE;
        }
    }

    public int getId() {
        return this.id;
    }
}
