package org.conscrypt.metrics;

/* JADX INFO: compiled from: r8-map-id-bab227d27872676e62ff2ffe2fded003c9d885b8c3013765058fc121ecc85da5 */
/* JADX INFO: loaded from: classes.dex */
public enum CipherSuite {
    UNKNOWN_CIPHER_SUITE(0),
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA),
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA),
    TLS_RSA_WITH_AES_256_CBC_SHA(53),
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA),
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA),
    TLS_RSA_WITH_AES_128_CBC_SHA(47),
    TLS_RSA_WITH_3DES_EDE_CBC_SHA(10),
    TLS_RSA_WITH_AES_128_GCM_SHA256(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_RSA_WITH_AES_128_GCM_SHA256),
    TLS_RSA_WITH_AES_256_GCM_SHA384(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_RSA_WITH_AES_256_GCM_SHA384),
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256),
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384),
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256),
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384),
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256),
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256),
    TLS_PSK_WITH_AES_128_CBC_SHA(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_PSK_WITH_AES_128_CBC_SHA),
    TLS_PSK_WITH_AES_256_CBC_SHA(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_PSK_WITH_AES_256_CBC_SHA),
    TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA),
    TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA),
    TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256),
    TLS_AES_128_GCM_SHA256(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_AES_128_GCM_SHA256),
    TLS_AES_256_GCM_SHA384(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_AES_256_GCM_SHA384),
    TLS_CHACHA20_POLY1305_SHA256(org.conscrypt.metrics.ConscryptStatsLog.TLS_HANDSHAKE_REPORTED__CIPHER_SUITE__TLS_CHACHA20_POLY1305_SHA256),
    TLS_CIPHER_FAILED(65535);

    final int id;

    CipherSuite(int i) {
        this.id = i;
    }

    public static org.conscrypt.metrics.CipherSuite forName(java.lang.String str) {
        if ("SSL_RSA_WITH_3DES_EDE_CBC_SHA".equals(str)) {
            return TLS_RSA_WITH_3DES_EDE_CBC_SHA;
        }
        try {
            return valueOf(str);
        } catch (java.lang.IllegalArgumentException unused) {
            return UNKNOWN_CIPHER_SUITE;
        }
    }

    public int getId() {
        return this.id;
    }
}
